import type { Analysis, StudentResult, ExportOptions } from "@/types";

// ─── CSV Export ───────────────────────────────────────────────────────────────

export function exportToCSV(analysis: Analysis, options: ExportOptions) {
  const { students } = analysis;
  if (!students || students.length === 0) return;

  const allSubjects = getUniqueSubjects(students);

  // Build headers
  const headers = ["Seat No", "Name"];
  allSubjects.forEach((subj) => {
    headers.push(
      `${subj}[faTh]`,
      `${subj}[saTh]`,
      `${subj}[faPr]`,
      `${subj}[saPr]`,
      `${subj}[sla]`,
      `${subj}[credits]`
    );
  });
  headers.push("totalmarks", "percentage", "totalcredits", "remark", "final status");

  // Build rows
  const rows = students.map((student) => {
    const row: (string | number)[] = [student.seatNo, student.name];
    allSubjects.forEach((subjName) => {
      const subj = student.subjects.find((s) => s.subjectName === subjName);
      row.push(
        subj?.faTh ?? "",
        subj?.saTh ?? "",
        subj?.faPr ?? "",
        subj?.saPr ?? "",
        subj?.sla ?? "",
        subj?.credits ?? ""
      );
    });
    row.push(student.totalMarks, student.percentage, student.totalCredit, student.remarks, student.finalStatus);
    return row;
  });

  // Add watermark row if free
  if (options.includeWatermark) {
    rows.push(["", "Generated by MSBTE Result Analyzer"]);
  }

  const csvContent = [
    `# ${analysis.departmentName} — Semester ${analysis.semesterNumber}`,
    `# Generated: ${new Date().toLocaleString()}`,
    "",
    headers.join(","),
    ...rows.map((row) =>
      row
        .map((cell) => {
          const str = String(cell);
          return str.includes(",") ? `"${str}"` : str;
        })
        .join(",")
    ),
  ].join("\n");

  const safeDeptName = analysis.departmentName.replace(/[^a-z0-9]/gi, '_');

  downloadFile(
    csvContent,
    `${safeDeptName}-Sem${analysis.semesterNumber}-${Date.now()}.csv`,
    "text/csv;charset=utf-8;"
  );
}

// Removed exportToPDF as requested

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getUniqueSubjects(students: StudentResult[]): string[] {
  const seen = new Set<string>();
  const subjects: string[] = [];
  students.forEach((s) => {
    s.subjects.forEach((subj) => {
      if (!seen.has(subj.subjectName)) {
        seen.add(subj.subjectName);
        subjects.push(subj.subjectName);
      }
    });
  });
  return subjects;
}

function downloadFile(content: string, filename: string, type: string) {
  // Add BOM for Excel compatibility
  const blob = new Blob(["\uFEFF" + content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
